name: thesis_studio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

scripts:
  clean: flutter clean && flutter pub get
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dart
  rxdart: ^0.28.0
  uuid: ^4.5.0
  path: ^1.9.0
  get_it: ^7.7.0
  sembast: ^3.7.3+3 # database
  json_annotation: ^4.9.0

  # flutter
  cupertino_icons: ^1.0.8
  re_editor: ^0.3.1
  re_highlight: ^0.0.3
  flutter_context_menu: ^0.2.0

  # plugin
  file_picker: ^8.1.2
  pdfrx: ^1.0.83
  community_material_icon: ^5.9.55
  path_provider: ^2.1.4
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  build_verify: any
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: vazirmtn
      fonts:
        - asset: assets/fonts/vazirmtn.ttf
    - family: vazir_code
      fonts:
        - asset: assets/fonts/vazir_code.ttf